name: Docker Hub Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Docker Hub Build & Push
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: kaviv23/learn-github-actions
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
